Repository tikv/importer, pull requests merged in 2019-08, with the labels that each got.

#12 config: stop using tikv's config struct; error on unrecognized fields
  Cargo.lock
  Cargo.toml
  rust-toolchain
  src/bin/tikv-importer.rs
  src/import/config.rs
  src/import/kv_server.rs
  src/import/mod.rs
  tests/integrations/import/kv_service.rs
Labels: release-blocker, status/LGT2

#14 bin: inline tikv::binutil::* so that CARGO_PKG_VERSION is the correct version
  src/bin/tikv-importer.rs
Labels: release-blocker, status/LGT1

#18 [3.0] Cargo.toml: update dependencies
  Cargo.lock
  Cargo.toml
Labels: status/LGT2

#19 kv_service: Add a `GetVersion` and `GetMetrics` gRPC endpoint
  Cargo.lock
  Cargo.toml
  Makefile
  rust-toolchain
  src/import/kv_service.rs
  src/import/metrics.rs
  src/import/service.rs
  src/import/test_helpers.rs
  tests/integrations/import/kv_service.rs
Labels: status/LGT2

#22 [3.0] Cargo.toml: bump version to 3.0.3
  Cargo.lock
  Cargo.toml
Labels: status/LGT2

#17 *: Change `WriteEngine` from a stream to a single message
  Cargo.lock
  Cargo.toml
  src/bin/tikv-importer.rs
  src/import/client.rs
  src/import/common.rs
  src/import/engine.rs
  src/import/errors.rs
  src/import/import.rs
  src/import/kv_importer.rs
  src/import/kv_service.rs
  src/import/prepare.rs
  src/import/service.rs
  src/import/stream.rs
  src/import/test_helpers.rs
  tests/integrations/import/kv_service.rs
Labels: status/LGT1
