Repository tikv/importer, pull requests merged in 2020-04, with the labels that each got.

#52 Cargo.toml: set version to 3.1.0-rc and update TiKV to release-3.1
  Cargo.lock
  Cargo.toml
  src/import/kv_server.rs
  src/import/service.rs
  src/import/stream.rs
  tests/integrations/import/kv_service.rs
Labels: release-blocker, status/LGT1

#56 Cargo.toml: set version to 3.1.0
  Cargo.lock
  Cargo.toml
Labels: release-blocker, status/LGT1

#57 use peer addr to resolve (#50)
  src/import/client.rs
Labels: status/LGT2

#58 Cargo.toml: set version to 3.0.13
  Cargo.lock
  Cargo.toml
Labels: release-blocker, status/PTAL

#59 *: upgrade to 4.0.0-rc.1.
  Cargo.lock
  Cargo.toml
  src/import/engine.rs
  src/import/status_server.rs
  tests/integrations/import/kv_service.rs
Labels: Should Update Docs, release-blocker, status/PTAL

#60 Cargo.toml: set version to 3.1.1
  Cargo.lock
  Cargo.toml
Labels: release-blocker, status/PTAL
