Repository tikv/importer, pull requests merged in 2020-03, with the labels that each got.

#44 Cherry-pick TLS support to release-3.0, and set version to v3.0.11
  Cargo.lock
  Cargo.toml
  Makefile
  etc/tikv-importer.toml
  src/import/client.rs
  src/import/engine.rs
  src/import/errors.rs
  src/import/kv_importer.rs
  src/import/kv_server.rs
  src/import/kv_service.rs
  src/import/prepare.rs
  src/import/stream.rs
  tests/integrations/import/kv_service.rs
Labels: release-blocker, status/LGT1

#47 Cargo.toml: set version to 4.0.0-beta.2
  Cargo.lock
  Cargo.toml
Labels: release-blocker, status/LGT1

#48 Cargo.toml: update tikv deps to release-3.0 and set version to 3.0.12
  Cargo.lock
  Cargo.toml
Labels: release-blocker, status/LGT2

#46 setup status server for profiling
  src/bin/tikv-importer.rs
  src/import/config.rs
  src/import/kv_server.rs
  src/import/mod.rs
  src/import/status_server.rs
Labels: status/LGT1

#50 Bug Fix: use peer_address to resolve rpc channel
  src/import/client.rs
Labels: status/LGT2

#38 Synchronize default config with documentation; Improve logs for diagnosis.
  Cargo.lock
  Cargo.toml
  etc/tikv-importer.toml
  src/import/common.rs
  src/import/config.rs
  src/import/engine.rs
  src/import/import.rs
  src/import/kv_importer.rs
  src/import/prepare.rs
  src/import/stream.rs
Labels: status/LGT2

#51 *: change tikv deps to release-4.0
  Cargo.lock
  Cargo.toml
  src/import/engine.rs
  src/import/errors.rs
  src/import/prepare.rs
  src/import/status_server.rs
Labels: status/LGT2
